include: package:flutter_lints/flutter.yaml

analyzer:
  # Üretilen (generated) dosyaları analiz dışı bırakıyoruz ki karmaşa olmasın
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "tools/**"

  # DART GÜÇLÜ MOD - Strict modları kapatıyoruz (mevcut kod uyumluluğu için)
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

  errors:
    # Mevcut tercihlerini korudum
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unintended_html_in_doc_comment: ignore

    # Warning ve info seviyesindeki kuralları ignore et
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_untyped_parameter: ignore

linter:
  rules:
    # Mevcut kuralların
    avoid_print: true
    prefer_single_quotes: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    use_super_parameters: false

    # Info seviyesi kuralları kapatıyoruz (mevcut kod için)
    unawaited_futures: false
    prefer_final_locals: false
    prefer_const_constructors: false
    avoid_void_async: false
    await_only_futures: true
    require_trailing_commas: false
    annotate_overrides: true
    avoid_unnecessary_containers: true
    prefer_is_not_empty: true         # .length > 0 yerine .isNotEmpty kullanmanı sağlar
    sort_child_properties_last: true  # Flutter widget ağacında 'child'ın en sonda olmasını sağlar